aruco_dictionary_name: "DICT_4X4_100"
aruco_marker_side_length: 0.10
camera_calibration_parameters_filename: "/home/snaak/Documents/manipulation_ws/src/handeye_calibration_ros2/handeye_realsense/realsense_info.yaml"
image_topic: "/camera/camera/color/image_rect_raw"
aruco_marker_name: "aruco_marker"
calculated_camera_optical_frame_name: "camera_color_optical_frame"
marker_data_file_name: "/home/snaak/Documents/manipulation_ws/src/handeye_calibration_ros2/handeye_realsense/resource/marker_data_realsense.yaml"
image_filename: "/home/snaak/Documents/manipulation_ws/src/handeye_calibration_ros2/handeye_realsense/resource/marker_pose_realsense_{pose_count}.jpg"
robot_data_file_name: "/home/snaak/Documents/manipulation_ws/src/handeye_calibration_ros2/handeye_realsense/resource/robot_data_realsense.yaml"
handeye_result_file_name: "/home/snaak/Documents/manipulation_ws/src/handeye_calibration_ros2/handeye_realsense/resource/handeye_result_realsense.yaml"
handeye_result_profile_file_name: "/home/snaak/Documents/manipulation_ws/src/handeye_calibration_ros2/handeye_realsense/resource/handeye_result_realsense_profile.yaml"

base_link: "panda_link_0"
ee_link: "panda_hand"
world_frame: "world"
